apiVersion: v2
name: fleet-crd
description: Fleet Manager CustomResourceDefinitions
version: 100.0.2+up0.3.8
appVersion: 0.3.8
icon: https://charts.rancher.io/assets/logos/fleet.svg
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/namespace: cattle-fleet-system
  catalog.cattle.io/release-name: fleet-crd
  catalog.cattle.io/os: linux
